/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Loan {
  'id' : LoanId,
  'status' : LoanStatus,
  'pending_amount' : bigint,
  'total_returned' : bigint,
  'created_at' : Timestamp,
  'amount_given' : bigint,
  'given_date' : string,
  'notes' : string,
  'given_by' : Principal,
  'given_to' : string,
}
export type LoanId = bigint;
export type LoanStatus = { 'active' : null } |
  { 'completed' : null };
export interface Repayment {
  'id' : RepaymentId,
  'loan_id' : LoanId,
  'amount_returned' : bigint,
  'return_date' : string,
  'notes' : string,
  'returned_by' : Principal,
}
export type RepaymentId = bigint;
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Result_1 = { 'ok' : RepaymentId } |
  { 'err' : string };
export type Timestamp = bigint;
export interface _SERVICE {
  'addRepayment' : ActorMethod<[LoanId, bigint, string, string], Result_1>,
  'createLoan' : ActorMethod<[string, bigint, string, string], LoanId>,
  'deleteLoan' : ActorMethod<[LoanId], Result>,
  'getLoan' : ActorMethod<[LoanId], [] | [Loan]>,
  'getLoans' : ActorMethod<[], Array<Loan>>,
  'getRepayments' : ActorMethod<[LoanId], Array<Repayment>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];