/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LoanId = IDL.Nat;
export const RepaymentId = IDL.Nat;
export const Result_1 = IDL.Variant({ 'ok' : RepaymentId, 'err' : IDL.Text });
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const LoanStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Loan = IDL.Record({
  'id' : LoanId,
  'status' : LoanStatus,
  'pending_amount' : IDL.Nat,
  'total_returned' : IDL.Nat,
  'created_at' : Timestamp,
  'amount_given' : IDL.Nat,
  'given_date' : IDL.Text,
  'notes' : IDL.Text,
  'given_by' : IDL.Principal,
  'given_to' : IDL.Text,
});
export const Repayment = IDL.Record({
  'id' : RepaymentId,
  'loan_id' : LoanId,
  'amount_returned' : IDL.Nat,
  'return_date' : IDL.Text,
  'notes' : IDL.Text,
  'returned_by' : IDL.Principal,
});

export const idlService = IDL.Service({
  'addRepayment' : IDL.Func(
      [LoanId, IDL.Nat, IDL.Text, IDL.Text],
      [Result_1],
      [],
    ),
  'createLoan' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [LoanId],
      [],
    ),
  'deleteLoan' : IDL.Func([LoanId], [Result], []),
  'getLoan' : IDL.Func([LoanId], [IDL.Opt(Loan)], ['query']),
  'getLoans' : IDL.Func([], [IDL.Vec(Loan)], ['query']),
  'getRepayments' : IDL.Func([LoanId], [IDL.Vec(Repayment)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LoanId = IDL.Nat;
  const RepaymentId = IDL.Nat;
  const Result_1 = IDL.Variant({ 'ok' : RepaymentId, 'err' : IDL.Text });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const LoanStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Loan = IDL.Record({
    'id' : LoanId,
    'status' : LoanStatus,
    'pending_amount' : IDL.Nat,
    'total_returned' : IDL.Nat,
    'created_at' : Timestamp,
    'amount_given' : IDL.Nat,
    'given_date' : IDL.Text,
    'notes' : IDL.Text,
    'given_by' : IDL.Principal,
    'given_to' : IDL.Text,
  });
  const Repayment = IDL.Record({
    'id' : RepaymentId,
    'loan_id' : LoanId,
    'amount_returned' : IDL.Nat,
    'return_date' : IDL.Text,
    'notes' : IDL.Text,
    'returned_by' : IDL.Principal,
  });
  
  return IDL.Service({
    'addRepayment' : IDL.Func(
        [LoanId, IDL.Nat, IDL.Text, IDL.Text],
        [Result_1],
        [],
      ),
    'createLoan' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [LoanId],
        [],
      ),
    'deleteLoan' : IDL.Func([LoanId], [Result], []),
    'getLoan' : IDL.Func([LoanId], [IDL.Opt(Loan)], ['query']),
    'getLoans' : IDL.Func([], [IDL.Vec(Loan)], ['query']),
    'getRepayments' : IDL.Func([LoanId], [IDL.Vec(Repayment)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };