/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type RepaymentId = bigint;
export interface Loan {
    id: LoanId;
    status: LoanStatus;
    pending_amount: bigint;
    total_returned: bigint;
    created_at: Timestamp;
    amount_given: bigint;
    given_date: string;
    notes: string;
    given_by: Principal;
    given_to: string;
}
export interface Repayment {
    id: RepaymentId;
    loan_id: LoanId;
    amount_returned: bigint;
    return_date: string;
    notes: string;
    returned_by: Principal;
}
export type LoanId = bigint;
export type Result_1 = {
    __kind__: "ok";
    ok: RepaymentId;
} | {
    __kind__: "err";
    err: string;
};
export enum LoanStatus {
    active = "active",
    completed = "completed"
}
export interface backendInterface {
    addRepayment(loan_id: LoanId, amount_returned: bigint, return_date: string, notes: string): Promise<Result_1>;
    createLoan(given_to: string, amount_given: bigint, given_date: string, notes: string): Promise<LoanId>;
    deleteLoan(id: LoanId): Promise<Result>;
    getLoan(id: LoanId): Promise<Loan | null>;
    getLoans(): Promise<Array<Loan>>;
    getRepayments(loan_id: LoanId): Promise<Array<Repayment>>;
}
import type { Loan as _Loan, LoanId as _LoanId, LoanStatus as _LoanStatus, RepaymentId as _RepaymentId, Result as _Result, Result_1 as _Result_1, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addRepayment(arg0: LoanId, arg1: bigint, arg2: string, arg3: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.addRepayment(arg0, arg1, arg2, arg3);
                return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRepayment(arg0, arg1, arg2, arg3);
            return from_candid_Result_1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createLoan(arg0: string, arg1: bigint, arg2: string, arg3: string): Promise<LoanId> {
        if (this.processError) {
            try {
                const result = await this.actor.createLoan(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLoan(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteLoan(arg0: LoanId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLoan(arg0);
                return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLoan(arg0);
            return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLoan(arg0: LoanId): Promise<Loan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoan(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoan(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLoans(): Promise<Array<Loan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoans();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoans();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRepayments(arg0: LoanId): Promise<Array<Repayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRepayments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRepayments(arg0);
            return result;
        }
    }
}
function from_candid_LoanStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoanStatus): LoanStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Loan_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Loan): Loan {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Loan]): Loan | null {
    return value.length === 0 ? null : from_candid_Loan_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LoanId;
    status: _LoanStatus;
    pending_amount: bigint;
    total_returned: bigint;
    created_at: _Timestamp;
    amount_given: bigint;
    given_date: string;
    notes: string;
    given_by: Principal;
    given_to: string;
}): {
    id: LoanId;
    status: LoanStatus;
    pending_amount: bigint;
    total_returned: bigint;
    created_at: Timestamp;
    amount_given: bigint;
    given_date: string;
    notes: string;
    given_by: Principal;
    given_to: string;
} {
    return {
        id: value.id,
        status: from_candid_LoanStatus_n8(_uploadFile, _downloadFile, value.status),
        pending_amount: value.pending_amount,
        total_returned: value.total_returned,
        created_at: value.created_at,
        amount_given: value.amount_given,
        given_date: value.given_date,
        notes: value.notes,
        given_by: value.given_by,
        given_to: value.given_to
    };
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _RepaymentId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: RepaymentId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
}): LoanStatus {
    return "active" in value ? LoanStatus.active : "completed" in value ? LoanStatus.completed : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Loan>): Array<Loan> {
    return value.map((x)=>from_candid_Loan_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
